# Generated by Django 3.1.4 on 2021-01-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('location_id', models.IntegerField()),
                ('uuid', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
    ]
