# Generated by Django 3.1.5 on 2021-02-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_familyplanningregistrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyplanningregistrations',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
