# Generated by Django 3.1.5 on 2021-02-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_familyplanningregistrations_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyplanningregistrations',
            name='gender',
        ),
        migrations.AddField(
            model_name='familyplanningregistrations',
            name='client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
