# Generated by Django 3.1.5 on 2021-02-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_auto_20210206_0117'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='familyplanningregistrations',
            table='family_planning_services',
        ),
    ]
