# Generated by Django 2.1.3 on 2020-06-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], max_length=30, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.CharField(blank=True, max_length=255, null=True)),
                ('date_edited', models.DateField(blank=True, max_length=255, null=True)),
                ('city_village', models.CharField(blank=True, default='unknown', max_length=255, null=True)),
                ('landmark', models.CharField(blank=True, default='unknown', max_length=255, null=True)),
                ('type', models.CharField(blank=True, default='Client', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('Family Member Registration', 'Family Member Registration'), ('Family Planning Registration', 'Family Planning Registration'), ('Introduction to Family Planning', 'Introduction to Family Planning'), ('Family Planning Pregnancy Screening', 'Family Planning Pregnancy Screening'), ('Family Planning Method Choice', 'Family Planning Method Choice'), ('Give Family Planning Method', 'Give Family Planning Method'), ('Update Family planning Registration', 'Update Family planning Registration'), ('Family Planning Change Method', 'Family Planning Change Method'), ('Fp Follow Up Visit', 'Fp Follow Up Visit'), ('Fp Follow Up Visit Resupply', 'Fp Follow Up Visit Resupply'), ('Fp Follow Up Visit Counselling', 'Fp Follow Up Visit Counselling'), ('Family Planning Discontinuation', 'Family Planning Discontinuation'), ('ANC Referral', 'ANC Referral'), ('Family Planning Referral', 'Family Planning Referral'), ('Family Planning Referral Followup', 'Family Planning Referral Followup')], max_length=100, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('team_id', models.CharField(blank=True, max_length=255, null=True)),
                ('location_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Events',
            },
        ),
    ]
