# Generated by Django 2.1.3 on 2020-06-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientextended',
            name='client_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
