# Generated by Django 2.1.3 on 2020-09-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
