# Generated by Django 2.1.3 on 2020-04-27 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city_village',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='date_edited',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='landmark',
            field=models.CharField(default='unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(default='Client', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True),
        ),
    ]
