# Generated by Django 2.1.3 on 2020-09-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='givefpmethod',
            name='coc_given',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='givefpmethod',
            name='number_of_pills',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='givefpmethod',
            name='pop_given',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='givefpmethod',
            name='sdm_given',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
