# Generated by Django 2.1.3 on 2020-06-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventextended',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
