# Generated by Django 2.1.3 on 2020-05-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=255)),
                ('referral_date', models.DateTimeField()),
                ('referral_type', models.CharField(blank=True, choices=[('Family Planning Referral', 'Family Planning Referral'), ('Other Referral', 'Other Referral')], max_length=100, null=True)),
                ('team', models.CharField(max_length=255)),
                ('team_id', models.CharField(max_length=255)),
                ('location_id', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Referrals',
            },
        ),
        migrations.RenameModel(
            old_name='Client',
            new_name='FamilyPlanningRegistration',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AlterModelTable(
            name='familyplanningregistration',
            table='FamilyPlanningRegistrations',
        ),
    ]
