# Generated by Django 2.1.3 on 2020-06-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='open_srp_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='open_srp_id',
        ),
    ]
