# Generated by Django 2.1.3 on 2020-06-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_edited',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
