# Generated by Django 2.1.3 on 2020-06-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_clientextended_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientextended',
            name='date_time_created',
        ),
    ]
