# Generated by Django 2.1.3 on 2020-08-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_clients_household'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('team_id', models.CharField(blank=True, max_length=255, null=True)),
                ('location_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_status', models.CharField(blank=True, max_length=255, null=True)),
                ('chw_referral_service', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_date', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_type', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_appointment_date', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_time', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'reerrals',
            },
        ),
        migrations.CreateModel(
            name='ReferralTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('for_entity', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('focus', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('requester', models.CharField(blank=True, max_length=255, null=True)),
                ('businessStatus', models.CharField(blank=True, max_length=255, null=True)),
                ('reasonReference', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'referral_task',
            },
        ),
    ]
