# Generated by Django 2.1.3 on 2020-04-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200427_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Referral', 'Referral'), ('Family Planning', 'Family Planning')], max_length=30)),
                ('provider_id', models.CharField(max_length=255)),
                ('event_date', models.DateTimeField()),
                ('team', models.CharField(max_length=255)),
                ('team_id', models.CharField(max_length=255)),
                ('location_id', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Event',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
