# Generated by Django 2.1.3 on 2020-09-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200915_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='givefpmethod',
            name='end',
        ),
        migrations.RemoveField(
            model_name='givefpmethod',
            name='start',
        ),
    ]
