# Generated by Django 2.1.3 on 2020-06-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200624_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventextended',
            old_name='field_code_7',
            new_name='obs_7_field_code_7',
        ),
        migrations.RenameField(
            model_name='eventextended',
            old_name='field_data_type_7',
            new_name='obs_7_field_data_type_7',
        ),
        migrations.RenameField(
            model_name='eventextended',
            old_name='field_type_7',
            new_name='obs_7_field_type_7',
        ),
        migrations.RenameField(
            model_name='eventextended',
            old_name='form_submission_field_7',
            new_name='obs_7_form_submission_field_7',
        ),
        migrations.RenameField(
            model_name='eventextended',
            old_name='human_readable_values_7',
            new_name='obs_7_human_readable_values_7',
        ),
        migrations.RenameField(
            model_name='eventextended',
            old_name='parent_code_7',
            new_name='obs_7_parent_code_7',
        ),
        migrations.RenameField(
            model_name='eventextended',
            old_name='values_7',
            new_name='obs_7_values_7',
        ),
    ]
