# Generated by Django 2.1.3 on 2020-11-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20201110_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
                ('team_id', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('location_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('base_entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('form_submission_id', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_task', models.CharField(blank=True, max_length=100, null=True)),
                ('referral_task_previous_status', models.CharField(blank=True, max_length=100, null=True)),
                ('referral_task_previous_business_status', models.CharField(blank=True, max_length=100, null=True)),
                ('service_provided', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'close_referral',
            },
        ),
    ]
