# Generated by Django 2.1.3 on 2020-09-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200905_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
