# Generated by Django 2.1.3 on 2020-06-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200609_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='created',
        ),
    ]
