# Generated by Django 2.1.3 on 2020-09-07 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200905_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='birth_Date',
            new_name='birth_date',
        ),
    ]
