# Generated by Django 2.1.3 on 2020-11-10 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_closereferral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closereferral',
            name='base_entity_id',
        ),
        migrations.RemoveField(
            model_name='closereferral',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='closereferral',
            name='form_submission_id',
        ),
        migrations.RemoveField(
            model_name='closereferral',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='closereferral',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='closereferral',
            name='team',
        ),
        migrations.RemoveField(
            model_name='closereferral',
            name='team_id',
        ),
    ]
