# Generated by Django 2.1.3 on 2020-06-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200624_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventextended',
            old_name='obs_7_field_code_7',
            new_name='obs_7_field_code',
        ),
        migrations.RenameField(
            model_name='eventextended',
            old_name='obs_7_field_data_type_7',
            new_name='obs_7_field_data_type',
        ),
        migrations.RenameField(
            model_name='eventextended',
            old_name='obs_7_field_type_7',
            new_name='obs_7_field_type',
        ),
        migrations.RenameField(
            model_name='eventextended',
            old_name='obs_7_form_submission_field_7',
            new_name='obs_7_form_submission_field',
        ),
        migrations.RenameField(
            model_name='eventextended',
            old_name='obs_7_human_readable_values_7',
            new_name='obs_7_human_readable_values',
        ),
        migrations.RenameField(
            model_name='eventextended',
            old_name='obs_7_parent_code_7',
            new_name='obs_7_parent_code',
        ),
        migrations.RenameField(
            model_name='eventextended',
            old_name='obs_7_values_7',
            new_name='obs_7_values_0',
        ),
    ]
