# Generated by Django 2.1.3 on 2020-04-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200427_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Referral', 'Referral'), ('Family Registration', 'Family Registration'), ('Family Planning Registration', 'Family Planning Registration'), ('Family Member Registration', 'Family Member Registration')], max_length=30),
        ),
    ]
