# Generated by Django 2.1.3 on 2020-06-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_client_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='created',
            new_name='testing',
        ),
    ]
