# Generated by Django 2.1.3 on 2020-06-16 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20200616_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientextended',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
