# Generated by Django 2.1.3 on 2020-11-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20201110_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closereferral',
            name='service_provided',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
