# Generated by Django 2.1.3 on 2020-06-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20200624_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventextended',
            old_name='obs_7_field_code',
            new_name='obs_1_field_code',
        ),
        migrations.RenameField(
            model_name='eventextended',
            old_name='obs_7_field_data_type',
            new_name='obs_1_field_data_type',
        ),
        migrations.RenameField(
            model_name='eventextended',
            old_name='obs_7_field_type',
            new_name='obs_1_field_type',
        ),
        migrations.RenameField(
            model_name='eventextended',
            old_name='obs_7_form_submission_field',
            new_name='obs_1_form_submission_field',
        ),
        migrations.RenameField(
            model_name='eventextended',
            old_name='obs_7_human_readable_values',
            new_name='obs_1_human_readable_values',
        ),
        migrations.RenameField(
            model_name='eventextended',
            old_name='obs_7_parent_code',
            new_name='obs_1_parent_code',
        ),
        migrations.RenameField(
            model_name='eventextended',
            old_name='obs_7_values_0',
            new_name='obs_1_values_0',
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_2_field_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_2_field_data_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_2_field_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_2_form_submission_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_2_human_readable_values',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_2_parent_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_2_values_0',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_3_field_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_3_field_data_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_3_field_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_3_form_submission_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_3_human_readable_values',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_3_parent_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_3_values_0',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_4_field_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_4_field_data_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_4_field_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_4_form_submission_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_4_human_readable_values',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_4_parent_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventextended',
            name='obs_4_values_0',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
