# Generated by Django 2.1.3 on 2020-08-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20200831_0932'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='referraltask',
            table='referral_tasks',
        ),
    ]
