# Generated by Django 2.1.3 on 2020-06-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20200625_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventextended',
            name='values_0',
            field=models.DateField(blank=True, null=True),
        ),
    ]
