# Generated by Django 2.1.3 on 2020-09-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20200907_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
