# Generated by Django 2.1.3 on 2020-11-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20201110_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closereferral',
            name='referral_task_previous_business_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='closereferral',
            name='service_provided',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
