# Generated by Django 2.1.3 on 2020-08-31 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20200831_0935'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='referral',
            table='referrals',
        ),
    ]
