# Generated by Django 2.1.3 on 2020-06-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20200609_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='testing',
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
