# Generated by Django 2.1.3 on 2020-06-18 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_clientextended_date_time_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientextended',
            old_name='client_id',
            new_name='client',
        ),
    ]
