# Generated by Django 2.1.3 on 2020-05-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20200502_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city_village',
            field=models.CharField(blank=True, default='unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='landmark',
            field=models.CharField(blank=True, default='unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(blank=True, default='Client', max_length=100, null=True),
        ),
    ]
