# Generated by Django 2.1.3 on 2020-06-26 13:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20200626_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventextended',
            name='values_0',
            field=models.DateField(default=datetime.datetime(2020, 6, 26, 13, 38, 6, 37123, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
