# Generated by Django 2.1.3 on 2020-06-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20200618_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientextended',
            name='date_time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
