# Generated by Django 2.1.3 on 2020-09-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20200831_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referraltask',
            old_name='businessStatus',
            new_name='businessstatus',
        ),
    ]
