# Generated by Django 2.1.3 on 2020-06-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20200626_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventextended',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
