# Generated by Django 2.1.3 on 2020-09-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20200902_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='referraltask',
            name='execution_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
