# Generated by Django 2.1.3 on 2020-11-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20201110_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='closereferral',
            name='location_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
