# Generated by Django 2.1.3 on 2020-11-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_closereferral_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='closereferral',
            name='base_entity_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='closereferral',
            name='event_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='closereferral',
            name='form_submission_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='closereferral',
            name='provider_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='closereferral',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='closereferral',
            name='team_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='closereferral',
            name='location_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
