# Generated by Django 2.1.3 on 2020-11-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20201111_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='referraltask',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
