# Generated by Django 2.1.3 on 2020-11-18 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_clients_base_entity_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='family_location_name',
            new_name='family',
        ),
    ]
