# Generated by Django 3.1.4 on 2021-01-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_auto_20201118_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('location_uuid', models.CharField(max_length=255)),
                ('location_name', models.CharField(max_length=255)),
                ('team_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'team_members',
            },
        ),
    ]
