# Generated by Django 3.1.4 on 2021-01-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_teammembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='location_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
