# Generated by Django 3.1.5 on 2021-01-31 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_team'),
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reg_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.location'),
        ),
    ]
