from django.urls import path
from UserManagement import views

urlpatterns = [
    path('', views.get_login_page, name='get_login_page'),
    path('user', views.authenticate_user, name='authenticate_user'),
    path('dashboard', views.get_dashboard, name='dashboard'),
    path('filter_dashboard', views.filter_dashboard, name='filter_dashboard'),
    path('logout', views.logout, name='logout'),
    path('geo_maps', views.get_geo_maps_page, name='geo_maps'),
    path('team_management', views.get_team_management_page, name='team_management'),
    path('location_management', views.get_location_management_page, name='location_management'),
    path('methods', views.get_methods_page, name='methods'),
    path('filtered_methods', views.get_filtered_methods_page, name='filtered_methods'),
    path('health_education', views.get_health_education_report, name='health_education'),
    path('filtered_health_education', views.get_filtered_health_education_report, name='filtered_health_education'),
    path('chw_performance', views.get_chw_performance_report, name='chw_performance'),
    path('filter_chw_performance', views.get_filtered_chw_performance_report, name='filter_chw_performance'),
    path('clients_summary', views.get_client_summary, name='clients_summary'),
    path('filter_clients', views.get_filtered_client_summary, name='filter_clients'),
    path('referrals_summary', views.get_referrals_summary, name='referrals_summary'),
    path('filter_referrals_summary', views.get_filtered_referrals_summary, name='filter_referrals_summary'),
    path('visits_summary', views.get_visit_summary, name='visits_summary'),
    path('filter_visit_summary', views.filter_visit_summary, name='filter_visit_summary'),
    path('initiations_summary', views.get_initiations_summary, name='initiations_summary'),
    path('discontinuations_summary', views.get_discontinuations_summary, name='discontinuations_summary'),
    path('citizens_report_summary', views.get_citizen_report_summary, name='citizens_report_summary'),
    path('filter_citizen_report_summary', views.filter_citizen_report_summary, name='filter_citizen_report_summary'),
    path('get_locations', views.get_locations, name='get_locations'),
    path('household_themes', views.get_household_page, name='household_themes'),
    path('export_clients_xls', views.export_clients_xls, name='export_clients_xls'),
    path('change_password', views.change_password, name='change_password'),
    path('save_changed_password/', views.set_changed_password, name='save_changed_password'),

]